---
- name: setup firewall
  import_tasks: firewall.yml

- name: ACI | Run kube proxy
  run_once: true
  import_role:
     name: kube_proxy_and_dns

- name: Deploy aci
  shell: oc apply -f {{ aci_deployment_yaml_file }}
  delegate_to: "{{ groups.oo_first_master.0 }}"
  run_once: True

